### ISSUE TITLE
We could not load resource configuration. Refresh page to try again

### ISSUE THREAD

**Issue by itsgsurya** [awslabs/aws-perspective#137]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html

)

---

**Describe the bug**
We could not load resource configuration. Refresh page to try again
Discovery process is scanning resources in 25 region(s) (always )

**To Reproduce**
After login to Perspective console

**Expected behavior**
A description of what you expected to happen.

**Screenshots**

**Browser (please complete the following information):**

- Name [chrome]
- Version [ v1.0.0]

**Additional context**

**Comment by svozza** [comment]
Hi there, could you confirm that it's not this issue: #98?

**Comment by itsgsurya** [comment]
I have applied the #98. Still the same problem. It's not showing any data on my console.  I have found the import errors in my container task. 
We have onboarded more than 25 accounts, is there any scalbilty issue ?  
![Screen Shot 2021-04-29 at 09 08 38](https://user-images.githubusercontent.com/25867181/116514079-cb251f80-a8ca-11eb-8f33-e5dd662c71f7.png)
![Screen Shot 2021-04-29 at 09 03 57](https://user-images.githubusercontent.com/25867181/116514083-cbbdb600-a8ca-11eb-8587-3074196299ae.png)


any idea?

**Comment by svozza** [comment]
Both of those errors are spurious and have been fixed in in v1.1.0, I'm think it might be this: https://github.com/awslabs/aws-perspective/issues/51. If you go to the filters and select a single account and refresh the page do you see resources?

**Comment by itsgsurya** [comment]
my container task is not running properly.  I have below errors container logsas well.

2021-04-29 10:02:27
/code/node_modules/gremlin/node_modules/ws/lib/websocket.js:270
/code/node_modules/gremlin/node_modules/ws/lib/websocket.js:270
2021-04-29 10:02:27
throw err;
2021-04-29 10:02:27
^
^
2021-04-29 10:02:27
Error: WebSocket is not open: readyState 2 (CLOSING)
Error: WebSocket is not open: readyState 2 (CLOSING)
2021-04-29 10:02:27
at WebSocket.ping (/code/node_modules/gremlin/node_modules/ws/lib/websocket.js:264:19)
at WebSocket.ping (/code/node_modules/gremlin/node_modules/ws/lib/websocket.js:264:19)
2021-04-29 10:02:27
at Timeout._onTimeout (/code/node_modules/gremlin/lib/driver/connection.js:222:16)
at Timeout._onTimeout (/code/node_modules/gremlin/lib/driver/connection.js:222:16)
2021-04-29 10:02:27
at listOnTimeout (internal/timers.js:531:17)
at listOnTimeout (internal/timers.js:531:17)
2021-04-29 10:02:27
at processTimers (internal/timers.js:475:7)
at processTimers (internal/timers.js:475:7)
2021-04-29 10:02:27
{"message":"No of nodes: 35944 No of edges: 1930786","level":"info"}
2021-04-29 10:01:14
{"message":"connected","level":"info"}
2021-04-29 10:01:14
{"message":"Loading previously discovered resources","level":"info"}
2021-04-29 10:01:14
{"message":"Connecting to Neptune","level":"info"}
2021-04-29 10:01:14
{"message":"CanImportRun Error:","level":"error"}
{"message":"CanImportRun Error:","level":"error"}
2021-04-29 10:01:14
{"message":"No duplicate tasks found so allowing discovery to run.","level":"info"}
2021-04-29 10:01:14
{"message":"Starting import using the following configuration:","level":"info"}
2021-04-29 10:01:14

**Comment by svozza** [comment]
Ah okay, that stacktrace is an error I've seen before and again, it's fixed in v1.1.0. I can give you the code to fix it locally and if you follow the steps in #98, you can build the container with the fix as a workaround?

**Comment by itsgsurya** [comment]
yes, please share the code . I will build a container based on #98, steps.

**Comment by svozza** [comment]
Replace the line [here](https://github.com/awslabs/aws-perspective/blob/eb09a26f20b7fa04e2d49030f27515c953052594/source/backend/discovery/src/discovery/db.js#L580):

```js
const data = await (getAllNodesAndEdges(g).finally(() => dc.close()));
```

with

```js
const data = await getAllNodesAndEdges(g)
        .finally(async () => {
            dc._client._connection._ws.terminate();
            await dc.close().catch(err => logger.error('Error closing Neptune DB connection ' + err))
        });
```

You might also need to update ECS task defintion to use the new version of the container that you've built.

**Comment by itsgsurya** [comment]
I have updated the above code. Still, no date showing in the console. I have the below errors.  any idea about the permissions issue.



![Screen Shot 2021-04-29 at 11 47 59](https://user-images.githubusercontent.com/25867181/116532646-c1a6b200-a8e0-11eb-893c-e76eb10f7b25.png)


![Screen Shot 2021-04-29 at 11 45 08](https://user-images.githubusercontent.com/25867181/116532285-5bba2a80-a8e0-11eb-9bb5-e5cc04fb251a.png)
.

**Comment by svozza** [comment]
Looks like their's something wrong with the `ZoomDiscoveryRole` IAM role in account 3655xxxx. Did it get installed properly?

**Comment by itsgsurya** [comment]
How we can verify whether it's installed properly or not?

One more thing below issues not resolved. I have applied the #98.  and followed the steps for Debugging the discovery component. Also your code as well. Unfortunately, I am getting still the same error message.  

![Screen Shot 2021-04-30 at 09 11 55](https://user-images.githubusercontent.com/25867181/116662174-b6fa2480-a995-11eb-9e4d-7a3e1275b7b4.png)

**Comment by svozza** [comment]
To check if the IAM role is installed properly, go to the account 3xxxxx and do a search in the IAM role console for `ZoomDiscoveryRole`.

I can see from those logs that you have 36039 resources. For the 'could not load resource configuration' error I think what's most likely is happening is that the lambda function that returns all the resources has a payload that is larger than 6mb so it's failing. If you see in #27, someone else encountered this issue. If you enable the filters and ask it to return only a single account for example does the error work?

Regarding the discovery service error, can you verify that the ECS task is using the new version of the Docker container? Go to `ECS -> Task Definitions -> aws-perspective-<accountId>-taskgroup` and click on the `JSON` tab. Search for the `image` field in the `containerDefinition` and ensure that the image version there matches the latest version in `ECR -> ECR
Repositories -> perspectivecontainerrepo-<randonString>`.

**Comment by itsgsurya** [comment]
I have checked the problem aws accounts unfortunately the ZoomDiscoveryRole missing. To solve these issues do I need to reimport the accounts or create the roles manually on missing accounts.

After applying the filter the issue has been disappeared.  Do we have a permanent solution for this issue?

I have checked my container task definition still it's taking the old image.   Could you please guide me on how I can update the task group? Sorry for the newbie question.

i did following  ECS -> Task Definitions -> aws-perspective-<accountId>-taskgroup -> Create new revision -> configure via JSON --> modified the image path to new ->create
After that  it's create the another task group,but it is not running  automaticaly 
![image](https://user-images.githubusercontent.com/25867181/116853300-1b1b2380-abf6-11eb-89f9-b8b69339cec6.png)

I appreciate your patience.

**Comment by svozza** [comment]
You need to go to  `Clusters -> aws-perspective-<account-no>-cluster -> aws-perspective-<account-no>-rule`, click on `Edit` and change the version of the task it's using there.

**Comment by itsgsurya** [comment]
Now I have update my container task definition It's using a new image. But I am facing the same issue and nothing changes in the Discovery process.


Container task errors.
2021-05-04 15:47:41/code/node_modules/gremlin/node_modules/ws/lib/websocket.js:270
2021-05-04 15:47:41throw err;
2021-05-04 15:47:41^
2021-05-04 15:47:41Error: WebSocket is not open: readyState 2 (CLOSING)
2021-05-04 15:47:41at WebSocket.ping (/code/node_modules/gremlin/node_modules/ws/lib/websocket.js:264:19)
2021-05-04 15:47:41at Timeout._onTimeout (/code/node_modules/gremlin/lib/driver/connection.js:222:16)
2021-05-04 15:47:41at listOnTimeout (internal/timers.js:531:17)
2021-05-04 15:47:41at processTimers (internal/timers.js:475:7)
2021-05-04 15:47:41{"message":"No of nodes: 36217 No of edges: 1923035","level":"info"}
2021-05-04 15:46:25{"message":"connected","level":"info"}
2021-05-04 15:46:24{"message":"Connecting to Neptune","level":"info"}
2021-05-04 15:46:24{"message":"Loading previously discovered resources","level":"info"}
2021-05-04 15:46:24{"message":"CanImportRun Error:","level":"error"}
2021-05-04 15:46:24{"message":"No duplicate tasks found so allowing discovery to run.","level":"info"}
2021-05-04 15:46:24{"message":"Starting import using the following configuration:","level":"info"}

![Screen Shot 2021-05-04 at 16 45 50](https://user-images.githubusercontent.com/25867181/117022038-32423a00-acf8-11eb-8dd4-7727e8f7db62.png)

**Comment by itsgsurya** [comment]
also below errors as well.

2021-05-04 16:51:34{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:34{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:34{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:33{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:33{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:33{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:33{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:32{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:32{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:31{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:31{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:31{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:31{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:31{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:31{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:31{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:31{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:30{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:30{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:30{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:30{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:30{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:30{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:30{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:30{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:30{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:30{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:30{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:30{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:30{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:30{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:30{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:30{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:30{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:30{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:30{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:30{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:29{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:29{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:29{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:29{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:29{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:29{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:29{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:29{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:26{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:26{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:26{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:26{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:26{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:26{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:26{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:26{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:24{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:24{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:24{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:24{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:24{"message":"callAwsApi error:","level":"error"}
2021-05-04 16:51:24{"message":"Error Message: You have specified a resource that is either unknown or has not been discovered.","level":"error"}
2021-05-04 16:51:24{"message":"callAwsApi error:","level":"error"}

**Comment by svozza** [comment]
Wait, is the Discovery process failing or not? Does it carry on after the db error above?

**Comment by svozza** [comment]
> I have checked the problem aws accounts unfortunately the ZoomDiscoveryRole missing. To solve these issues do I need to reimport the accounts or create the roles manually on missing accounts.

I missed this btw, you just need to create the role in the accounts, no need to reimport as long as the accounts are visible in the UI. If you are able to use CloudFormation StackSets, it's a much quicker process than deploying the templates individually.

**Comment by itsgsurya** [comment]
The Discovery process not failing. I  have found multiple issues in my container tasks.  One of the container tasks was having the above DB issues  another  container task has  "callAwsApi error" issues

One more thing after updating the container mage the new task not stopping automatically. Please find the attached screenshots and error logs 

Could you please guide me to resolve the issue

 [container tasks errors.txt](https://github.com/awslabs/aws-perspective/files/6426370/container.tasks.errors.txt)

[container task2 error log.txt](https://github.com/awslabs/aws-perspective/files/6426371/container.task2.error.log.txt)
![Screen Shot 2021-05-05 at 11 11 50](https://user-images.githubusercontent.com/25867181/117127016-d7621e80-ad9b-11eb-8ff5-aac237c4da46.png)

**Comment by svozza** [comment]
Those `callAwsApi` errors are normally just either rate limiting errors coming back from calls to the AWS Config api that get retried with exponential back off or the discovery process trying to link nodes together when one hasn't been discovered yet, which disappear later when that other resource has been found. They can pretty much be ignored. 

I've not seen this multiple task issue before, are the tasks doing anything or does logging just stop at a certain time? 

The alarm error in the secondshot is not a problem, it's because missing data is been set to `breaching` rather than `notBreaching` when the alarm is set up. You can see here, for example:  https://github.com/awslabs/aws-perspective/blob/eb09a26f20b7fa04e2d49030f27515c953052594/source/cfn/templates/perspective-search.yaml#L101

This has been fixed in the new version.

The problem we saw initially was because the `zoomDiscoveryRole` was not deployed in some of the target accounts, without that, those accounts will always have permission denied issues and the discovery process won't write to DynamoDb to say it has completed it's scan of that account and its regions.

**Comment by itsgsurya** [comment]
Those Container tasks not stopping automatically and it's running forever.   I have stopped those tasks manually, is it something related to updated code?

Regarding the "zoomDiscoveryRole" issues account, I have deleted them from UI.

**Comment by itsgsurya** [comment]
@svozza  do we have any updates for  v1.1.0. release dates

**Comment by svozza** [comment]
> Those Container tasks not stopping automatically and it's running forever. I have stopped those tasks manually, is it something related to updated code?

I don't know why those tasks won't end but I do know why there are multiple tasks running, there is a bug in the IAM role the discovery service uses (again this has been fixed in v1.1.0). You can fix it manually if you go to `IAM -> Roles` and search for the `PerspectiveDiscoveryServerRole` role. Lok for the policy named `perspective-discovery-cluster` and then change it to this:

```json
{
  "PolicyName": "perspective-discovery-cluster",
  "PolicyDocument": {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Action": [
          "ecs:ListTasks"
        ],
        "Resource": "*",
        "Condition": {
          "ArnEquals": {
            "ecs:cluster": <your-cluster-ARN>
          }
        }
      }
    ]
  }
}
```

> @svozza do we have any updates for v1.1.0. release dates

I can't share dates publicly, we are currently in the final documentation stage of our release but this can take a varying amount of time depending on how much revisions the documentation must undergo.

**Comment by svozza** [comment]
Something just occurred to me about why your discovery process is taking so long. Can you go to the Neptune console and get me the CPU stats of the instance?

**Comment by itsgsurya** [comment]
Please find attached the last 24hrs CPU stats, it is pretty normal.  Now I am having another issue with my UI.  I am able to see my resources in UI, but I am not able to create the architecture diagrams.
<img width="1284" alt="Screen Shot 2021-05-07 at 13 18 20" src="https://user-images.githubusercontent.com/25867181/117442218-c13c9580-af36-11eb-807a-9cbf4119244e.png">

<img width="1214" alt="Screen Shot 2021-05-07 at 13 01 40" src="https://user-images.githubusercontent.com/25867181/117441904-5723f080-af36-11eb-88eb-ec74a6743b45.png">

**Comment by itsgsurya** [comment]
how I will get rid of this issue. any guidance.



{     "message": "CanImportRun Error:",     "level": "error" }
--
{     "message": "No duplicate tasks found so allowing discovery to run.",     "level": "info" }
{     "message": "Loading previously discovered resources",     "level": "info" }
{     "message": "Connecting to Neptune",     "level": "info" }
{     "message": "connected",     "level": "info" }
{     "code": 1006,     "message": "connection event: close",     "level": "info" }
(node:1) UnhandledPromiseRejectionWarning: Error: Neptune connection is closed
at AwsSigV4DriverRemoteConnection._closeHandler (/code/src/discovery/aws-sigv4-driver-remote-connection.js:233:32)
at Connection.<anonymous> (/code/src/discovery/aws-sigv4-driver-remote-connection.js:195:70)
at Connection.emit (events.js:314:20)
at Connection.EventEmitter.emit (domain.js:483:12)
at Connection._handleClose (/code/node_modules/gremlin/lib/driver/connection.js:239:10)
at WebSocket.<anonymous> (/code/node_modules/gremlin/lib/driver/connection.js:132:50)
at WebSocket.emit (events.js:314:20)
at WebSocket.EventEmitter.emit (domain.js:483:12)
at WebSocket.emitClose (/code/node_modules/gremlin/node_modules/ws/lib/websocket.js:191:10)
at TLSSocket.socketOnClose (/code/node_modules/gremlin/node_modules/ws/lib/websocket.js:850:15)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.





(node:1) UnhandledPromiseRejectionWarning: Error: Neptune connection is closed
--
at AwsSigV4DriverRemoteConnection._closeHandler (/code/src/discovery/aws-sigv4-driver-remote-connection.js:233:32)
at Connection.<anonymous> (/code/src/discovery/aws-sigv4-driver-remote-connection.js:195:70)
at Connection.emit (events.js:314:20)
at Connection.EventEmitter.emit (domain.js:483:12)
at Connection._handleClose (/code/node_modules/gremlin/lib/driver/connection.js:239:10)
at WebSocket.<anonymous> (/code/node_modules/gremlin/lib/driver/connection.js:132:50)
at WebSocket.emit (events.js:314:20)
at WebSocket.EventEmitter.emit (domain.js:483:12)
at WebSocket.emitClose (/code/node_modules/gremlin/node_modules/ws/lib/websocket.js:191:10)
at TLSSocket.socketOnClose (/code/node_modules/gremlin/node_modules/ws/lib/websocket.js:850:15)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by svozza** [comment]
Does the discovery process die after you see that error?

**Comment by itsgsurya** [comment]
@svozza I am unable to solve our aws-perspective stack issues. Currently, it is very slow and not showing the diagrams properly. Because of my above issues, we are planning to re-deploy the stack from scratch. Is it worth waiting for a new release, what are your thoughts?
Could you please share a rough timeline ( I mean the number of weeks).

**Comment by thebutler12** [comment]
Please create a new issue tagged with v1.1.0 if you are still experiencing this issue.
