### ISSUE TITLE
Cost from replicated cross-account Cost and Usage Report not showing up in diagrams.

### ISSUE THREAD

**Issue by quasitime** [awslabs/aws-perspective#148]
**Describe the bug**

We are attempting to get the cost data to show up in diagrams associated with various resources.
For the main account perspective is running in, cost data is showing up correctly from what we can tell.
From imported account with CUR replicated into the same bucket, we are not seeing cost data show up in the resources associated with the imported account.

-We are seeing discovered resources from the external imported account, and can manipulated/filter those resources in Perspective.
-We are seeing the cost and usage reports from the imported account replicated correctly into the main cost S3 bucket, in appropriate folders as zip files.
-Verified that the permissions on the bucket allow the cost lambda access to all objects in the bucket.
-Also correctly seeing cost data from the main perspective account.

**To Reproduce**

1.  Import another account into Perspective and deploy the cloudformation template in that account.
2. Verifiy discovery is showing resources from imported account.
3. Enable Cost & Usage Report per documentation in external account.
4. Enable Replication into S3 bucket in main Perspective account
5. Verify cost data is showing or not showing for imported account.

**Expected behavior**
We expect to see cost data associated with resources from the imported account.

**Screenshots**
Could add screenshots but really the cost data just shows up as $0.00

**Browser (please complete the following information):**

- Firefox
- 87

**Additional context**

**Comment by svozza** [comment]
It's most likely this issue: https://github.com/awslabs/aws-perspective/issues/141. Can you check the cost lambda function to confirm? As I said in that issue, we have rewritten the cost feature from scratch in v1.1.0 so this will not be a problem in the future.

**Comment by quasitime** [comment]
I'm not seeing that error, but when I search all log groups associated with the cost lambda, I see a couple instances of this one in the past 12 hours:

ERROR	Forbidden: null
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/services/s3.js:698:35)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9) {
  code: 'Forbidden',
  region: null,
  time: 2021-04-29T10:32:41.022Z,

<snipped out some of the request ID metadata>

**Comment by quasitime** [comment]
(The cost lambda is using the default execution role created by the stack that has complete access to the S3 bucket)

**Comment by thebutler12** [comment]
Please create a new issue tagged with v1.1.0 if you are still experiencing this issue.
