### ISSUE TITLE
Gremlin - Certificate Has Expired

### ISSUE THREAD

**Issue by leozhad** [awslabs/aws-perspective#32]
**Describe the bug**
Discovery is broken.

**To Reproduce**
In Gremlin Lambda Function Function Logs, I see this: 

```2020-09-24T16:03:36.985Z	[redacted]	INFO	Error connecting to neptune:  Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12) {
  code: 'CERT_HAS_EXPIRED',
  config: {
    url: 'https://perspective-dev-cluster.cluster-[redacted].us-east-1.neptune.amazonaws.com:6174/status',
    headers: {
      Accept: 'application/json, text/plain, */*',
      Host: 'perspective-dev-cluster.cluster-[redacted].us-east-1.neptune.amazonaws.com:6174',
      'X-Amz-Security-Token': [redcted]',
      'X-Amz-Date': '20200924T160336Z',
      Authorization: 'AWS4-HMAC-SHA256 Credential=[redacted]/20200924/us-east-1/neptune-db/aws4_request, SignedHeaders=host;x-amz-date;x-amz-security-token, Signature=[redacted]',
      'User-Agent': 'axios/0.19.2'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 3000,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    method: 'get',
    data: undefined
  },
  request: Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      protocol: 'https:',
      maxRedirects: 21,
      maxBodyLength: 10485760,
      path: '/status',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'perspective-dev-cluster.cluster-[redacted].us-east-1.neptune.amazonaws.com',
      port: '6174',
      nativeProtocols: [Object],
      pathname: '/status'
    },
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET /status HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Host: perspective-dev-cluster.cluster-[redacted].us-east-1.neptune.amazonaws.com:6174\r\n' +
        'X-Amz-Security-Token: [redacted]' +
        'X-Amz-Date: 20200924T160336Z\r\n' +
        'Authorization: AWS4-HMAC-SHA256 Credential=[redacted]/20200924/us-east-1/neptune-db/aws4_request, SignedHeaders=host;x-amz-date;x-amz-security-token, Signature=[redacted]\r\n' +
        'User-Agent: axios/0.19.2\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/status',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Circular],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://perspective-dev-cluster.cluster-[redacted].us-east-1.neptune.amazonaws.com:6174/status',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function]
}
```

**Comment by toksvaeth** [comment]
Investigation with @leozhad has yielded information that this issue was identified to be an account specific bug not pertaining to Perspective and has since been resolved.

If anyone sees this again in the future please open a new issue and we'll look into it.
